name: hello-world

on: 
  push:

jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Print hello_world.txt
        run: echo "$(cat hello_world.txt)"
